name: Nuxt.js GitHub CI

on:
  push:
    branches:
      - master

jobs:
  clone:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/tshopkz
            git pull origin master
            npm i
  
  build:
    runs-on: ubuntu-latest
    needs: clone
    
    steps:
      - uses: actions/checkout@master
        
      - name: Build
        uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm i
      - run: npm run build
      
      - name: Deploy
        uses: nogsantos/scp-deploy@master
        with:
          src: ./.nuxt
          host: ${{ secrets.SSH_HOST }}
          remote: /var/www/tshopkz
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
      
