name: Node Github CI

on:
  push:
    branches:
      - dist

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: SSH and deploy node app
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www
          rm -rf tshopkz
          git clone -b dist git@github.com:etozhealkhipce/tshopkz.git
          cd tshopkz
          npm install
          pm2 start
